// Generates supabase/seed.sql from src/data/pillars.content.json.
// Run from the website/ dir:  node supabase/generate-seed.mjs
// Re-run whenever you change the JSON so the DB seed stays in sync.
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const here = dirname(fileURLToPath(import.meta.url));
const jsonPath = join(here, '..', 'src', 'data', 'pillars.content.json');
const outPath = join(here, 'seed.sql');

const { pillars } = JSON.parse(readFileSync(jsonPath, 'utf-8'));

// Single-quote escaping for SQL string literals.
const q = (v) => (v === null || v === undefined ? 'null' : `'${String(v).replace(/'/g, "''")}'`);

const lines = [];
lines.push('-- AUTO-GENERATED by supabase/generate-seed.mjs — do not edit by hand.');
lines.push('-- Run this in the Supabase SQL Editor AFTER schema.sql.');
lines.push('-- Safe to re-run: it clears both tables first.');
lines.push('');
lines.push('truncate table public.projects, public.pillars restart identity cascade;');
lines.push('');

lines.push('insert into public.pillars (slug, label, description, sort_order) values');
const pillarRows = pillars.map(
  (p, i) => `  (${q(p.slug)}, ${q(p.label)}, ${q(p.description)}, ${i})`,
);
lines.push(pillarRows.join(',\n') + ';');
lines.push('');

lines.push(
  'insert into public.projects (id, pillar_slug, category, title, agency, status, progress, budget, description, source, source_url, sort_order) values',
);
const projectRows = [];
for (const p of pillars) {
  const groups = [
    ['Objectives', p.objectives],
    ['Policies', p.policies],
    ['Projects', p.projects],
  ];
  for (const [category, items] of groups) {
    items.forEach((it, i) => {
      projectRows.push(
        `  (${q(it.id)}, ${q(p.slug)}, ${q(category)}, ${q(it.title)}, ${q(it.agency)}, ` +
          `${q(it.status)}, ${it.progress}, ${q(it.budget)}, ${q(it.description)}, ` +
          `${q(it.source)}, ${q(it.sourceUrl ?? null)}, ${i})`,
      );
    });
  }
}
lines.push(projectRows.join(',\n') + ';');
lines.push('');

writeFileSync(outPath, lines.join('\n'), 'utf-8');
console.log(`Wrote ${outPath} (${pillars.length} pillars, ${projectRows.length} projects)`);
